services:
  database:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: web
      POSTGRES_PASSWORD: JCCnyw0melL5S2O-nkiXK4IvTH-1AFx4MMim-Q6S0uo
      POSTGRES_DB: specklesDb
    volumes:
      - "db_storage:/var/lib/postgresql/data/"
    ports:
      - "5432:5432"

  api:
    build:
      context: ./
      dockerfile: ./Speckles.Api/Dockerfile
    restart: always
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - JWT_SECRET=${JWT_SECRET}
  
#  frontend:
#    depends_on:
#      - api
#      - database
#    restart: always
#    build:
#      context: ./
#      dockerfile: ./Speckles.Frontend/Dockerfile
#    ports:
#      - "3000:3000"
#    environment:
#      - NODE_ENV=production

volumes:
  db_storage:
    driver: local