app = "speckles-api"

[build]
  # Assuming you're building your API with a Dockerfile
  dockerfile = "./Speckles.Api/Dockerfile"
  context = "."

[env]
  # Environment variables for your API service
  ASPNETCORE_ENVIRONMENT = "Development"
  POSTGRES_USER = "web"
  POSTGRES_PASSWORD = "JCCnyw0melL5S2O-nkiXK4IvTH-1AFx4MMim-Q6S0uo"
  POSTGRES_DB = "specklesDb"
  DATABASE_URL = "postgres://web:JCCnyw0melL5S2O-nkiXK4IvTH-1AFx4MMim-Q6S0uo@speckles.internal:5432/specklesDb" # Replace with the actual URL from Fly managed PostgreSQL

[[services]]
  internal_port = 80
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
